Room creation and image attribute
GCES-2018-2/SIGS-GCES pull request #292
Opened 2019-09-18 17:15 UTC by GeovanaRamos

## Proposed Changes
Added room creation for admins and image field for each room.

## _Issue_ Related

https://github.com/SIGS-UnB/core/issues/232
https://github.com/SIGS-UnB/core/issues/233

## Type of Changes

- [X] New backend feature or update.
- [X] New frontend feature or update.
- [ ] Bug fix.
- [ ] Another change (what was the change?).

## Checklist

- [X] This Pull Request has a significant name.
- [X] The commits follow the [[commits policy]].
- [ ] The build is okay (tests, code climate).
- [X] This Pull Request mentions a related issue.
- [ ] The change was necessary to the progress of the project.

## Screenshots

![newroom](https://user-images.githubusercontent.com/31005087/65170209-8ebaed80-da1e-11e9-8830-627eb43c8e9d.png)
![showroom2](https://user-images.githubusercontent.com/31005087/65170211-8ebaed80-da1e-11e9-844e-5f7348293253.png)
![showrooom](https://user-images.githubusercontent.com/31005087/65170213-8f538400-da1e-11e9-93b7-986f348025df.png)
![indexrooms](https://user-images.githubusercontent.com/31005087/65170214-8f538400-da1e-11e9-82a3-41b14d530987.png)

2019-09-18 17:21 UTC, filypsdias commented
How can we (@filypsdias & @CaioGabrielAraujo ) be assigned to this PR?

2019-10-22 14:21 UTC, arthurbdiniz commented on app/views/rooms/index.html.erb
> +
No extra line here

2019-10-22 14:25 UTC, arthurbdiniz requested changes
Just some style changes to do here

2019-10-22 14:25 UTC, arthurbdiniz commented on app/models/room.rb
> +  has_one_attached :photo
This statement should be on the top with:

```ruby
class Room < ApplicationRecord
  belongs_to :building
  has_many :allocations, dependent: :destroy
  belongs_to :department
  has_and_belongs_to_many :category
  belongs_to :department
```

2019-10-22 14:25 UTC, arthurbdiniz commented on app/views/rooms/index.html.erb
> +
No extra line here

2019-10-23 13:38 UTC, GeovanaRamos commented
@arthurbdiniz a test that was passing now is broken for no reason. Any ideias? I only removed a blank line and changed the attribute line.

2019-10-23 14:53 UTC, GeovanaRamos commented
Found a test that sometimes was breaking and sometimes was not! It's all good now.

2019-10-23 19:11 UTC, arthurbdiniz approved these changes

2019-10-23 19:12 UTC, merged